env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  project:
    - './tsconfig.json'
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - react
rules:
  '@typescript-eslint/consistent-type-exports': error
  '@typescript-eslint/consistent-type-imports': error
  '@typescript-eslint/no-explicit-any': error
root: true
